### ISSUE TITLE
The project is marked as deprecated in the summary

### ISSUE THREAD

**Issue by withrocks** [Deathspike/HtmlAgilityPack-PCL#2]
Why is the library currently marked as deprecated?

**Comment by Deathspike** [comment]
The main project supposedly has PCL support now. If not, this will still work.

I currently use HAP anymore either way.

**Comment by withrocks** [comment]
Ok, thanks for clearing that up. I had some issues with xpath with the latest version of the main project and assumed it was related to PCL, but hadn't looked into that further. I'll take a closer look at this but will close the ticket.
